from .wildberries import search_wildberries
from .ozon import search_ozon
from .yandex_market import search_yandex_market
from .goldapple import search_goldapple
from .letual import search_letual
from .podruzka import search_podruzka
from .magnit_cosmetic import search_magnit_cosmetic
from .rivgosh import search_rivgosh
from .iledebeaute import search_iledebeaute
from .svyetofor import search_svyetofor
from .apteka366 import search_apteka366
from .aliexpress import search_aliexpress
